steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/byword-intake-api', '.']

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/byword-intake-api']

  # Step 3: Deploy to Cloud Run -> byword-intake-api
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'byword-intake-api'         # ✅ This is your correct service name
      - '--image=gcr.io/$PROJECT_ID/byword-intake-api'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/byword-intake-api'
